commands:
  helloWorld:
    run: |
      echo "Hello World!"
      echo "Hello World again!"
    description: Displays "Hello World!"
  interactiveCommand:
    run: |
      bash -c 'read -p"Please type some text: " myVariable && echo "You typed \"${myVariable}\""'
      echo "If you can see this we've confirmed that the instruction after the interactive command is also run..."
  build:
    run: pnpm run build
    description: Build the project cheat sheet project.
  run:
    run: pnpm run start
    description: Build and run the project.
  test:
    run: pnpm run test
    description: Test the project cheat sheet project.
