commands:
  helloWorld:
    run: |
      echo "Hello World!"
      echo "Hello World again!"
    description: Displays "Hello World!"
  build:
    run: pnpm run build
    description: Build the project cheat sheet project.
  run:
    run: pnpm run start
    description: Build and run the project.
  test:
    run: pnpm run test
    description: Test the project cheat sheet project.
